spring.application.name=CrowdData
server.port=8095
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

springdoc.api-docs.title=CrowdData API Documentation
springdoc.api-docs.description=API for Managing crowdsourced data

spring.datasource.url=jdbc:sqlite:./database
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
