# spring application
spring.application.name=gateway
server.port=8090

# spring cloud gateway configuration
app:
	crowdSourcedDataApi: http://localhost:8091
	rewardServiceApi: http://localhost:8092

# spring cloud config
spring.cloud.config.enabled=false

# management endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

# logging levels
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=WARN